# Generated by Django 4.2.7 on 2023-11-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('descriptions', models.TextField(verbose_name='Описание сайта')),
                ('logo', models.ImageField(upload_to='logo_image', verbose_name='Логотоип сайта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=255, verbose_name='Телейонный номер')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Ссылка на Youtube')),
            ],
            options={
                'verbose_name': ('Основные параметры',),
                'verbose_name_plural': 'Основные параметры',
            },
        ),
    ]
