# Generated by Django 4.2.7 on 2023-11-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='history_image_1', verbose_name='Первая фотография')),
                ('image_2', models.ImageField(upload_to='history_image_2', verbose_name='Второя фотография')),
                ('decriptions', models.TextField(verbose_name='Описание истории')),
            ],
        ),
    ]
