# Generated by Django 4.2.7 on 2023-11-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': ('Наша история',), 'verbose_name_plural': 'Наша история'},
        ),
        migrations.RenameField(
            model_name='history',
            old_name='decriptions',
            new_name='descriptions',
        ),
    ]
