# Generated by Django 4.2.7 on 2023-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reservation_image', verbose_name='Фотография')),
                ('descriptions', models.TextField(verbose_name='Описание блюда')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('date', models.CharField(max_length=255, verbose_name='Дата')),
                ('time', models.CharField(max_length=255, verbose_name='Время')),
                ('person', models.CharField(max_length=255, verbose_name='Количество человек')),
            ],
            options={
                'verbose_name': ('Забронировать',),
                'verbose_name_plural': 'Забронировать',
            },
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
