# Generated by Django 4.2.7 on 2023-11-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_reservation_delete_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='descriptions',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
