# Generated by Django 4.2.7 on 2023-11-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_reservation_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='reservation_image', verbose_name='Фотография')),
                ('job', models.CharField(max_length=255, verbose_name='Работа')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': ('Команда',),
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
